### ISSUE TITLE
Provide checksums, PGP sigs of release tarballs

### ISSUE THREAD

**Issue by ArchangeGabriel** [intel/thermal_daemon#108]
Hi @spandruvada,

Would you mind providing checksums and PGP sigs for release tarballs? Those would be great for enhanced security in retrieving the sources. ;) Please tell if you need help regarding PGP workflow in this end.

Also, I’m wondering why downloads are not offered on 01.org like they are for e.g. [beignet](https://01.org/beignet/downloads).

Thanks!

**Comment by spandruvada** [comment]
Hi,
On Sun, 2017-01-08 at 04:18 -0800, Bruno Pagani wrote:
> Hi @spandruvada,
> Would you mind providing checksums and PGP sigs for release tarballs?
Could you give some example of github projects using this for source
code download?


> Those would be great for enhanced security in retrieving the
> sources. ;) Please tell if you need help regarding PGP workflow in
> this end.
> Also, I’m wondering why downloads are not offered on 01.org like they
> are for e.g. beignet.
Those projects are not hosted in gihub so that is the only way to
provide source.

Thanks,
Srinivas

**Comment by ArchangeGabriel** [comment]
Sorry for the delay. While I’m searching for example, you can read on how to do this here: https://wiki.debian.org/Creating%20signed%20GitHub%20releases

**Comment by ArchangeGabriel** [comment]
(And obviously, the uses example is one: https://github.com/cinemast/libjson-rpc-cpp)

**Comment by ArchangeGabriel** [comment]
Other example: https://github.com/creshal/yspave/releases

Tell me if you need more, but I won’t spend time just for making a catalog of them. ;)

Also, about the above Debian link, I strongly encourage taking a look at the alternative method.

**Comment by spandruvada** [comment]
Hi Bruno,

The release tar balls are generated by github. I guess this procedure
to add additional step should be done by github based on some config.

Send a change, I will try.

Thanks,
Srinivas

**Comment by ArchangeGabriel** [comment]
Hi Srinivas,

No, GitHub can’t (and shouldn’t) do much more here (apart from verifying tag signature, which is a related but not required thing here). GitHub does indeed generate the tarball, but you can also reproduce this locally using this command (after setting tag to the actual tag name):
```
git archive --prefix="${tag}/" -o "../${tag}.tar.gz" "${tag}"
```

Then, you can sign it locally using your PGP key (but you don’t appear to have one, at least not a public one, so maybe the issue here is you don’t know about PGP/GPG?) with GnuPG for instance:
```
gpg --armor --detach-sign "../${tag}.tar.gz"
```

Then just attach the produced ${tag}.tar.gz.asc file at (replacing tag with the correct value):
https://github.com/01org/thermal_daemon/releases/edit/${tag}

For instance, with the current v1.5.4 release/tag:
```
tag=v1.5.4
git archive --prefix="${tag}/" -o "../${tag}.tar.gz" "${tag}"
gpg --armor --detach-sign "../${tag}.tar.gz"
```

And then upload `v1.5.4.tar.gz` to:
https://github.com/01org/thermal_daemon/releases/edit/v1.5.4

**Comment by spandruvada** [comment]
Hi Bruno,

Thanks for the procedure. I do have a PGP public key uploaded to github. Is there any other place I need to upload?

Thanks,
Srinivas

On Tue, 2017-01-31 at 04:51 -0800, Bruno Pagani wrote:

Hi Srinivas,

No, GitHub can’t (and shouldn’t) do much more here (apart from verifying tag signature, which is a related but not required thing here). GitHub does indeed generate the tarball, but you can also reproduce this locally using this command (after setting tag to the actual tag name):

git archive --prefix="${tag}/" -o "../${tag}.tar.gz" "${tag}"


Then, you can sign it locally using your PGP key (but you don’t appear to have one, at least not a public one, so maybe the issue here is you don’t know about PGP/GPG?) with GnuPG for instance:

gpg --armor --detach-sign "../${tag}.tar.gz"


Then just attach the produced ${tag}.tar.gz.asc file at (replacing tag with the correct value):
https://github.com/01org/thermal_daemon/releases/edit/${tag}<https://github.com/01org/thermal_daemon/releases/edit/$%7Btag%7D>

For instance, with the current v1.5.4 release/tag:

tag=v1.5.4
git archive --prefix="${tag}/" -o "../${tag}.tar.gz" "${tag}"
gpg --armor --detach-sign "../${tag}.tar.gz"


And then upload v1.5.4.tar.gz to:
https://github.com/01org/thermal_daemon/releases/edit/v1.5.4

**Comment by ArchangeGabriel** [comment]
Well that’s a good first step for signing commits and tags while having them verified by GitHub, but it still doesn’t provide packager a way to verify the sigs by themselves.

You should also upload your key to a public key server, using for instance `gpg --send-keys`. And start signing releases and eventually commits/tags. ;)
