### ISSUE TITLE
example configuration for two-socket server

### ISSUE THREAD

**Issue by ecnalubma** [intel/thermal_daemon#136]
Hi, I am using a two-socket server with two Xeon E5-2699v3 CPUs. The design of the server is such that one CPU always runs hotter than the other, as one CPU is cooled with air that has already warmed up passing over the other.

I would like to configure thermald to control each CPU's temperature completely independently, using RAPL, pstate and powerclamp, though I am not sure powerclamp even supports injecting idle time on a per-socket basis. I have tried to do this, without any success.

Would it be possible to provide either an example configuration for this type of setup, or a "complete" (if artificial) example configuration which demonstrates every single thermald capability?

**Comment by spandruvada** [comment]
It should be doable. First need to disable the default processing by setting some arbitrarily high temperature and then create a config file using core temp sysfs. I will try to create config file next week.

**Comment by ecnalubma** [comment]
Hi spandruvada, is there any update on this? Is it possible?

**Comment by spandruvada** [comment]
https://pastebin.com/semq58PU
Copy the data to "2_pkg_config.xml", which is passed as the input configuration for the test.

Build from the latest code from the master branch. I added an option to ignore all default control.

Stop the existing thermald service.

Run for test and then simulate temperature. You can lower trip temperature for experiments.

# sudo ./thermald --no-daemon --loglevel=info --ignore-default-control --config-file ./2_pkg_config.xml

**Comment by ecnalubma** [comment]
Unfortunately this doesn't work, as-is. After spending some time trying to get it to work, I see a few issues:

1) the power constraint seems to go in the wrong direction (when the thermal limit is exceeded, larger, not smaller, power constraints are written)

2) nonsense power constraints can be written (e.g. negative values) if the control loop doesn't get the desired thermal response.

3) the exponential gain/linear decay control loop seems inappropriate for RAPL. What I would expect is that when the devices are well under the thermal threshold value, the devices should quickly have the highest (maximum) RAPL constraint, and when they are over it, they should use quickly use lower and lower RAPL values until the minimum supported value is reached. If after this the devices return back under the thermal threshold, the devices should quickly return back to the highest RAPL constraint value. It is important here that these transitions occur quickly, it's not acceptable to have the transition in one direction be fast (exponential) and the other one slow (linear) because that means either the devices will run very hot for extended periods of time, or the devices will run very slowly even when there is no need for them to do so.

**Comment by spandruvada** [comment]
On Fri, 2017-11-10 at 05:17 +0000, ecnalubma wrote:

Unfortunately this doesn't work, as-is. After spending some time trying to get it to work, I see a few issues:

  1.  the power constraint seems to go in the wrong direction (when the thermal limit is exceeded, larger, not smaller, power constraints are written)

  2.  nonsense power constraints can be written (e.g. negative values) if the control loop doesn't get the desired thermal response.

  3.  the exponential gain/linear decay control loop seems inappropriate for RAPL. What I would expect is that when the devices are well under the thermal threshold value, the devices should quickly have the highest (maximum) RAPL constraint, and when they are over it, they should use quickly use lower and lower RAPL values until the minimum supported value is reached. If after this the devices return back under the thermal threshold, the devices should quickly return back to the highest RAPL constraint value. It is important here that these transitions occur quickly, it's not acceptable to have the transition in one direction be fast (exponential) and the other one slow (linear) because that means either the devices will run very hot for extended periods of time, or the devices will run very slowly even when there is no need for them to do so.

We can directly write limits by using TargetState attribute. Then this slow down and fast up logic won't kick in. Only disadvantage is that you should know what power to write for each temperature.
I have attached example config to use this attribute (not a two socket example). Here B0D4 is a rapl device. In your case you will have different rapl device for each CPU package.



Thanks,
Srinivas


  1.

**Comment by spandruvada** [comment]
I have tried on my 2 socket system with the config file as in
https://pastebin.com/88r74DYT

Here when temperature is reaching 48c I am limiting max power  to 100 Watt, and when temperature is 50C limiting to 50W or respective packages. This is working with 
# sudo ./thermald --no-daemon --loglevel=info --ignore-default-control --config-file ./2_pkg_config.xml

Make sure that you have --ignore-default -control option.
Tried with the latest version of thermald 1.7.1
