### ISSUE TITLE
decimal point vs. comma in config file

### ISSUE THREAD

**Issue by muetze** [intel/thermal_daemon#141]
example thermal-conf.xml shows:

  \<PidControl>
                           \<kp>0.001</kp>
                           \<kd>0.0001</kd>
                           \<ki>0.0001</ki>
 \</PidControl>"

Log:
...
	 PID: Kp 0,000000
	 PID: Ki 0,000000
	 PID: Kd 0,000000
...

So it shows decimal point. But instead, only comma is accepted:
If I change thermal-conf.xml to

 \<PidControl>
                           \<kp>0,001</kp>
                           \<kd>0,0001</kd>
                           \<ki>0,0001</ki>
 \</PidControl>

log shows:
...
	 PID: Kp 0,001000
	 PID: Ki 0,000100
	 PID: Kd 0,000100
...

version:
commit 4eacc9a2b031c97969ed754ea4d2c22bed92e2c4 
2017-09-22

**Comment by spandruvada** [comment]
On Mon, 2017-10-02 at 00:19 +0000, muetze wrote:
> example thermal-conf.xml shows:
> <PidControl>
> <kp>0.001
> <kd>0.0001
> <ki>0.0001
> </PidControl>"
> Log:
> ...
> PID: Kp 0,000000
> PID: Ki 0,000000
> PID: Kd 0,000000
This is printed using %f format and converted from string using atof()
while reading from config file. So it depends on your localization.
For some localization "," will be used instead of "."

thermald does look for "." or ","

# locale | grep LC_NUMERIC

Thanks,
Srinivas
