### ISSUE TITLE
[Thinkpad] Weird thermal behaviour and related questions

### ISSUE THREAD

**Issue by fthx** [intel/thermal_daemon#215]
Hi,

[Thinkpad T480s, i7 8550u, Ubuntu 20.04 dev, kernel 5.4, thermald 1.9.1, tlp 1.3beta4]

We have a discussion about excessive throttling in Thinkpads here : https://forums.lenovo.com/t5/Other-Linux-Discussions/X1C6-T480s-low-cTDP-and-trip-temperature-in-Linux/td-p/4028489/highlight/true/page/32

So : 

1. I installed the dptfxtract package (from Ubuntu repo), which created some config files in /etc/thermald, that I deleted all after uninstalling dptfxtract
2. I tried to put this in thermal-conf.xml : 
```
<!-- BEGIN -->
<ThermalConfiguration>
<Platform>
<Name>T480s</Name>
<ProductName>20L7CTO1WW</ProductName>
</Platform>
</ThermalConfiguration>
<!-- END -->
```

3. After restarting my pc I ran s-tui to stress it and checked that the bad : 
```
cpu 70 °C
freq 2300 MHz
fan  ~4000 rpm
```
became
```
cpu 95 °C
freq 2900 MHz
fan  ~5000 rpm
```
4. So, I was happy since the full performance was back (note that simply removing thermald does not change anything, except maybe a worse perf during the first seconds of a cpu load).

Nonetheless, there is still an issue : sometimes (e.g. resume from sleep) the perfs go back to the old behaviour (2300 MHz) and I don't know why. Restarting the thermal daemon via systemctl does recover the 2900 Mhz perfs.

So my questions : 
1. Why such a void thermal-conf.xml file makes the perfs better ?
2. Why the max perfs are sometimes lost and why restarting thermald does the trick ?

Thanks !

**Comment by fthx** [comment]
Another user found that bad perfs do happen after a cold boot or resume from sleep.
I can confirm.

**Comment by spandruvada** [comment]
On Sat, 2020-02-01 at 03:15 -0800, fthx wrote:

Hi,

[Thinkpad T480s, i7 8550u, Ubuntu 20.04 dev, kernel 5.4, thermald 1.9.1, tlp 1.3beta4]

We have a discussion about excessive throttling in Thinkpads here : https://forums.lenovo.com/t5/Other-Linux-Discussions/X1C6-T480s-low-cTDP-and-trip-temperature-in-Linux/td-p/4028489/highlight/true/page/32

So :

  1.  I installed the dptfxtract package (from Ubuntu repo), which created some config files in /etc/thermald, that I deleted all after uninstalling dptfxtract
  2.  I tried to put this in thermal-conf.xml :



<ThermalConfiguration>

<Platform>

<Name>T480s</Name>

<ProductName>20L7CTO1WW</ProductName>

</Platform>

</ThermalConfiguration>



  1.  After restarting my pc I ran s-tui to stress it and checked that the bad :

cpu 70 °C

freq 2300 MHz

fan  ~4000 rpm

became

cpu 95 °C

freq 2900 MHz

fan  ~5000 rpm

  1.  So, I was happy since the full performance was back (note that simply removing thermald does not change anything, except maybe a worse perf during the first seconds of a cpu load).

> Nonetheless, there is still an issue : sometimes (e.g. resume from
> sleep) the perfs go back to the old behaviour (2300 MHz) and I don't
> know why. Restarting the thermal daemon via systemctl does recover
> the 2900 Mhz perfs.workaround-enabled

So my questions :

  1.  Why such a void thermal-conf.xml file makes the perfs better ?Why the max perfs are sometimes lost and why restaring thermald does the trick ?

Does adding option helps?

-- workaround-enabled

Thanks,
Srinivas


Thanks !

**Comment by fthx** [comment]
Ok, thanks !

Cold boot (not a restart), AC plugged in, "--workaround-enabled" in systemd thermald service and no thermald restart.
Results during stress (all cpu cores used) : 
1. Without trivial thermal-conf.xml : 
fan 4690 rpm / cpu 2700 MHz / 20 W cpu / 30 W platform
2. With trivial thermal-conf.xml (see above) : 
fan 5090 rpm / cpu 2900 MHz / 25 W cpu / 38 W platform

So basically it works. Great ! I still don't understand what's the role of thermal-conf.xml here ?

**Comment by spandruvada** [comment]
On Sun, 2020-02-02 at 00:25 -0800, fthx wrote:

Ok, thanks !

Cold boot (not a restart), AC plugged in, "--workaround-enabled" in systemd thermald service and no thermald restart.
Results during stress (all cpu cores used) :

  1.  Without trivial thermal-conf.xml :
fan 4690 rpm / cpu 2700 MHz / 20 W cpu / 30 W platform
  2.  With trivial thermal-conf.xml (see above) :
fan 5090 rpm / cpu 2900 MHz / 25 W cpu / 38 W platform

So basically it works. Great ! I still don't understand what's the role of thermal-conf.xml here ?

I will not suggest changing output of dptfxtract utility. You can make temperature threshold less, not more.
Otherwise the system temperature will be beyond specs. thermald reads power/temperature limits from the output of dptfxtract. Sometimes those limits are also present in the sysfs, so using those limits assuming that user with root permission didn't mess with the output of dptfxtact in bad way.

**Comment by fthx** [comment]
Ok I edited : 
https://forums.lenovo.com/t5/Other-Linux-Discussions/X1C6-T480s-low-cTDP-and-trip-temperature-in-Linux/m-p/4637873#M14378

**Comment by fthx** [comment]
Hi Srinivas,

I noticed I do not need anymore the --workaround-enabled option in Ubuntu 20.04 dev (based on kernel 5.4.22). What is the change that caused this good news ?

**Comment by spandruvada** [comment]
Hi,
On Tue, 2020-03-03 at 23:42 -0800, Francois Thirioux wrote:

Hi Srinivas,

I noticed I do not need anymore the --workaround-enabled option in Ubuntu 20.04 dev (based on kernel 5.4.22). What is the change that caused this good news ?

This kernel has kernel interface to set tcc and power. Check by suspend/resume, AC/DC etc and see if this changes by stopping thermald. If it doesn't then workaround is not required.
#cat sys/bus/pci/devices/0000:00:04.0/tcc_offset_degree_celsius

Thanks,
Srinivas

**Comment by fthx** [comment]
Ok :
```
$ cat /sys/bus/pci/devices/0000:00:04.0/tcc_offset_degree_celsius
5

```
is stuck at 5 in any of your test cases.
But I still need thermald (without workaround) to reach CPU Tmax -- 5° .

**Comment by spandruvada** [comment]
Try new version which has adaptive version by default.

**Comment by fthx** [comment]
Yes I tried it and now use it since 5.8 kernel landing in Ubuntu 20.04 hwe-edge.
I use thermald 2.3 latest from 20.10 and the result is WAY better than 5.4/1.9.1, and without any hack.

Thanks.
