### ISSUE TITLE
[Dell Vostro 3491] rapl_controller too aggressive by default

### ISSUE THREAD

**Issue by ettlz** [intel/thermal_daemon#228]
I'm trying to set up thermald on a Dell Vostro 3491 notebook, with a i5-1035G1 processor. One thing I've noticed is that by default the constraint-0 power limit is set to 9W, with the max of 15W. When thermald uses rapl_controller to cool things it sets about 8.75W as a power limit which is very slow, around 1GHz with all cores running 100%. If I manually override the power limit to 15W I get a more reasonable 1.8GHz.

Is there some way I can configure thermald to use the 15W max power instead?

[I'm not convinced rapl_controller has been properly-implemented on this notebook. For instance it sticks around after thermald exits, and seems to persist even after rapl_controller has been removed from thermald's cooling devices list.]

**Comment by spandruvada** [comment]
On Sat, 2020-05-16 at 16:09 -0700, James wrote:

I'm trying to set up thermald on a Dell Vostro 3491 notebook, with a i5-1035G1 processor. One thing I've noticed is that by default the constraint-0 power limit is set to 9W, with the max of 15W. When thermald uses rapl_controller to cool things it sets about 8.75W as a power limit which is very slow, around 1GHz with all cores running 100%. If I manually override the power limit to 15W I get a more reasonable 1.8GHz.

Is there some way I can configure thermald to use the 15W max power instead?

[I'm not convinced rapl_controller has been properly-implemented on this notebook. For instance it sticks around after thermald exits, and seems to persist even after rapl_controller has been removed from thermald's cooling devices list.]

Look at this issue: https://bugs.launchpad.net/ubuntu/+source/thermald/+bug/1874933
This is getting backported.

Please try to run dptfxtract. Since you have 9W in this table means never used this table. You will see power limits in
/etc/thermald/thermal-conf.xml.auto. Hope this will fix for you.

If someone wants to fix power limits, it can be done in
/etc/thermald/thermal-conf.xml.auto

For example for 15W:

<?xml version="1.0"?>
 
 <ThermalConfiguration>
 <Platform>

        <Name> For test only </Name>
        <ProductName>*</ProductName>
        <Preference>QUIET</Preference>

        <PPCC>
                <PowerLimitIndex>0</PowerLimitIndex>
                <PowerLimitMinimum>5000</PowerLimitMinimum>
                <PowerLimitMaximum>15000</PowerLimitMaximum>
                <TimeWindowMinimum>28000</TimeWindowMinimum>
                <TimeWindowMaximum>32000</TimeWindowMaximum>
                <StepSize>500</StepSize>
        </PPCC>

        <ThermalZones>
                <ThermalZone>
...
...

**Comment by ettlz** [comment]
Marvellous -- thanks very much for your help. I later ran dptfextract and it gave me a config file with the PPCC block, but only 'TSKN' and 'TMEM' zones so I just replaced them with a straight cpu/passive 91C zone. This seems to do the job.

Could the PPCC tag be documented in the thermald man page?

**Comment by spandruvada** [comment]
On Sun, 2020-05-17 at 08:12 -0700, James wrote:

Marvellous -- thanks very much for your help. I later ran dptfextract and it gave me a config file with the PPCC block, but only 'TSKN' and 'TMEM' zones so I just replaced them with a straight cpu/passive 91C zone. This seems to do the job.

If not there, then OEM doesn't want any limit placed on CPU, they probably used the
Check
/sys/bus/pci/devices/0000:00:04.0/tcc_offset_degree_celsius
Lower means higher limit from the maximum temp.

Could the PPCC tag be documented in the thermald man page?

I should, didn't get time.

**Comment by ettlz** [comment]
The default tcc_offset_degress_celsius is 1 on this notebook with the latest firmware. It seems they rigged this machine to run _very_ close to the edge -- if I run stress on all cores it gets up to 98-100C within a few seconds before something kicks in to reduce the CPU speed (on both Linux and Windows). With thermald configured as above under load it stabilises at 15W; I've not yet completely characterised the machine's behaviour on Windows.

The machine also seems much more reluctant than other notebooks I've had to spin up the fans (sysfs control of which seems broken by ACPI BIOS bugs), regardless of the mode in smbios-thermal-ctl. For safety I'm now overriding tcc_offset_degree_celsius to 6; by design or not, I'd rather not routinely be hitting the CPU's max safe temperature!
