### ISSUE TITLE
Lower severity of warnings when probing

### ISSUE THREAD

**Issue by benzea** [intel/thermal_daemon#237]
thermald probes a number of locations in sysfs and the existence of configuration files. I do see the point of logging such failures as they may be interesting for debugging purposes. Unfortunately, logging them as is tends to confuse users into believing they are problematic (see also #205, which seems to have gotten derailed).

This came up in the F33 change proposal to ad thermald, see https://pagure.io/fesco/issue/2437#comment-664238
```
Jul 08 20:03:18 igors-t480s thermald[143083]: [1594231398][WARN]sensor id 10 : No temp sysfs for reading raw temp
Jul 08 20:03:18 igors-t480s thermald[143083]: [1594231398][WARN]sensor id 10 : No temp sysfs for reading raw temp
Jul 08 20:03:18 igors-t480s thermald[143083]: [1594231398][WARN]sensor id 10 : No temp sysfs for reading raw temp
Jul 08 20:03:18 igors-t480s thermald[143083]: I/O warning : failed to load external entity "/etc/thermald/thermal-conf.xml"
Jul 08 20:03:18 igors-t480s thermald[143083]: [1594231398][WARN]error: could not parse file /etc/thermald/thermal-conf.xml
Jul 08 20:03:18 igors-t480s thermald[143083]: [1594231398][WARN]sysfs open failed
Jul 08 20:03:18 igors-t480s thermald[143083]: I/O warning : failed to load external entity "/etc/thermald/thermal-conf.xml"
Jul 08 20:03:18 igors-t480s thermald[143083]: [1594231398][WARN]error: could not parse file /etc/thermald/thermal-conf.xml
Jul 08 20:03:18 igors-t480s thermald[143083]: I/O warning : failed to load external entity "/etc/thermald/thermal-conf.xml"
Jul 08 20:03:18 igors-t480s thermald[143083]: [1594231398][WARN]error: could not parse file /etc/thermald/thermal-conf.xml
```

**Comment by keszybz** [comment]
[c&p of my comment from the fesco ticket]

Please add ConditionVirtualization=no to thermald.service. This will already cut down the log spew quite a bit.

The logs that termald outputs are simply bad.
- "[1594231398][WARN]" — that's just noise. Thermald is logging to the journal, not to a text file, and any prefixes like that should be dropped.
- It also "warns" about the things which are completely normal and OK.
- And it repeats the same log lines over and over.

Log spew is not just a cosmetic issue, it makes usability of the machine worse. Users should be able to look at the logs from a boot and not have any lines at warning or higher level, unless there are actual problems to fix. Various services dump garbage to the logs and this makes it hard to debug anything when there are real problems, because the user is buried by "warnings" and "fatal errorz" that they need to wade through first. And users have no way to know how serious those issues really are.

**Comment by spandruvada** [comment]
Merged the patch.

**Comment by spandruvada** [comment]
Send me a pull request to downgrade these to info level.

**Comment by benzea** [comment]
Now it looks like this for me:
```
Jul 09 17:14:16 ben-x1c7 thermald[605382]: 22 CPUID levels; family:model:stepping 0x6:8e:c (6:142:12)
Jul 09 17:14:16 ben-x1c7 thermald[605382]: Polling mode is enabled: 4
Jul 09 17:14:16 ben-x1c7 thermald[605382]: sensor id 11 : No temp sysfs for reading raw temp
Jul 09 17:14:16 ben-x1c7 thermald[605382]: sensor id 11 : No temp sysfs for reading raw temp
Jul 09 17:14:16 ben-x1c7 thermald[605382]: sensor id 11 : No temp sysfs for reading raw temp
Jul 09 17:14:16 ben-x1c7 thermald[605382]: Using generated /var/run/thermald/thermal-conf.xml.auto
Jul 09 17:14:16 ben-x1c7 thermald[605382]: Using config file /var/run/thermald/thermal-conf.xml.auto
Jul 09 17:14:16 ben-x1c7 thermald[605382]: sysfs create failed
```

For the `sysfs create failed`, I created #239 as the code seems a bit weird to me that triggers it.
