### ISSUE TITLE
The family:model:stepping 0x6:55:7 is not support

### ISSUE THREAD

**Issue by os369510** [intel/thermal_daemon#290]
I have a HP Z4 workstation and the thermald is not active on it.

```
● thermald.service - Thermal Daemon Service
   Loaded: loaded (/lib/systemd/system/thermald.service; enabled; vendor preset: enabled)
   Active: inactive (dead) since Mon 2021-01-11 17:27:14 CST; 41min ago
  Process: 947 ExecStart=/usr/sbin/thermald --no-daemon --dbus-enable (code=exited, status=1/FAILURE)
 Main PID: 947 (code=exited, status=1/FAILURE)

-- Logs begin at Mon 2021-01-11 16:59:31 CST, end at Mon 2021-01-11 17:10:02 CST. --
 一 11 17:02:55 u-HP-Z4-G4-Workstation systemd[1]: Starting Thermal Daemon Service...
 一 11 17:02:55 u-HP-Z4-G4-Workstation thermald[3440]: 22 CPUID levels; family:model:stepping 0x6:55:7 (6:85:7)
 一 11 17:02:55 u-HP-Z4-G4-Workstation thermald[3440]: Need Linux PowerCap sysfs
 一 11 17:02:55 u-HP-Z4-G4-Workstation thermald[3440]: Unsupported cpu model, use thermal-conf.xml file or run with --ignore-cpuid-check
 一 11 17:02:55 u-HP-Z4-G4-Workstation thermald[3440]: THD engine start failed
 一 11 17:02:55 u-HP-Z4-G4-Workstation systemd[1]: Started Thermal Daemon Service.
```

May I know does the "Intel's server big cores" could be supported by thermald?

**Comment by spandruvada** [comment]
This is a server CPU, we don't add support for it by default. Try running  with option: --ignore-cpuid-check


On Mon, 2021-01-11 at 02:13 -0800, Jeremy Su wrote:

I have a HP Z4 workstation and the thermald is not active on it.

● thermald.service - Thermal Daemon Service
   Loaded: loaded (/lib/systemd/system/thermald.service; enabled; vendor preset: enabled)
   Active: inactive (dead) since Mon 2021-01-11 17:27:14 CST; 41min ago
  Process: 947 ExecStart=/usr/sbin/thermald --no-daemon --dbus-enable (code=exited, status=1/FAILURE)
 Main PID: 947 (code=exited, status=1/FAILURE)

-- Logs begin at Mon 2021-01-11 16:59:31 CST, end at Mon 2021-01-11 17:10:02 CST. --
 一 11 17:02:55 u-HP-Z4-G4-Workstation systemd[1]: Starting Thermal Daemon Service...
 一 11 17:02:55 u-HP-Z4-G4-Workstation thermald[3440]: 22 CPUID levels; family:model:stepping 0x6:55:7 (6:85:7)
 一 11 17:02:55 u-HP-Z4-G4-Workstation thermald[3440]: Need Linux PowerCap sysfs
 一 11 17:02:55 u-HP-Z4-G4-Workstation thermald[3440]: Unsupported cpu model, use thermal-conf.xml file or run with --ignore-cpuid-check
 一 11 17:02:55 u-HP-Z4-G4-Workstation thermald[3440]: THD engine start failed
 一 11 17:02:55 u-HP-Z4-G4-Workstation systemd[1]: Started Thermal Daemon Service.


May I know does the "Intel's server big cores" could be supported by thermald?

**Comment by os369510** [comment]
@spandruvada Hi, I got the other platforms. Those are using another Intel CPU.
```
processor	: 11
vendor_id	: GenuineIntel
cpu family	: 6
model		: 167
model name	: Intel(R) Xeon(R) W-1350P @ 4.00GHz
stepping	: 1
```
I didn't find it from https://en.wikichip.org/wiki/intel/cpuid
Would you please let me know whether it's a server CPU? thanks.

**Comment by chihchun** [comment]
@os369510 I assume the processes categorized[1] as Workstation will be see as server CPU.

[1] Intel® Xeon® W-1350P Processor https://ark.intel.com/content/www/us/en/ark/products/212264/intel-xeon-w-1350p-processor-12m-cache-up-to-5-10-ghz.html
