### ISSUE TITLE
Raptor Lake CPU ID family:model:stepping 0x6:b7:0 (6:183:0) is not include

### ISSUE THREAD

**Issue by xanthein** [intel/thermal_daemon#354]
The cpu id does not include in the table. Can this cpu be supported by thermald?

Here is the journal log when using Ubuntu 22.04 in new desktop platform

○ thermald.service - Thermal Daemon Service
     Loaded: loaded (/lib/systemd/system/thermald.service; enabled; vendor preset: enabled)
     Active: inactive (dead) since Fri 2022-06-17 10:56:42 CST; 2s ago
    Process: 3574 ExecStart=/usr/sbin/thermald --systemd --dbus-enable --adaptive (code=exited, status=0/SUCCESS)
   Main PID: 3574 (code=exited, status=0/SUCCESS)
        CPU: 8ms

Jun 17 10:56:42 ubuntu systemd[1]: Starting Thermal Daemon Service...
Jun 17 10:56:42 ubuntu systemd[1]: Started Thermal Daemon Service.
Jun 17 10:56:42 ubuntu thermald[3574]: 32 CPUID levels; family:model:stepping 0x6:b7:0 (6:183:0)
Jun 17 10:56:42 ubuntu thermald[3574]:  Need Linux PowerCap sysfs
Jun 17 10:56:42 ubuntu thermald[3574]: Unsupported cpu model or platform
Jun 17 10:56:42 ubuntu systemd[1]: thermald.service: Deactivated successfully.

**Comment by xanthein** [comment]
log files dump from thermal-debug-dump-ubuntu.s
[24100940.tar.gz](https://github.com/intel/thermal_daemon/files/8972713/24100940.tar.gz)
h

**Comment by xanthein** [comment]
@spandruvada can you help to take a look?

**Comment by spandruvada** [comment]
Please test
checkout branch thermald_2_5_devel
build and
run test/thermal-debug-dump-ubuntu.sh or Fedora equivalent and
send me logs.

**Comment by Kobatw** [comment]
with thermald_2_5_devel, the unsupported message is gone, 
but got theses error since,
 六  28 10:05:37 ubuntu systemd[1]: Started Thermal Daemon Service.
 六  28 10:05:37 ubuntu thermald[10860]: 32 CPUID levels; family:model:stepping 0x6:b7:0 (6:183:0)
 六  28 10:05:37 ubuntu thermald[10860]: 32 CPUID levels; family:model:stepping 0x6:b7:0 (6:183:0)
 六  28 10:05:37 ubuntu thermald[10860]: sensor id 6 : No temp sysfs for reading raw temp
 六  28 10:05:37 ubuntu thermald[10860]: sensor id 6 : No temp sysfs for reading raw temp
 六  28 10:05:37 ubuntu thermald[10860]: sensor id 6 : No temp sysfs for reading raw temp
 六  28 10:05:37 ubuntu thermald[10860]: Config file //etc/thermald/thermal-conf.xml does not exist
 六  28 10:05:37 ubuntu thermald[10860]: Config file //etc/thermald/thermal-conf.xml does not exist
 六  28 10:05:37 ubuntu thermald[10860]: Config file //etc/thermald/thermal-conf.xml does not exist
 六  28 10:05:37 ubuntu thermald[10860]: Polling mode is enabled: 4

**Comment by xanthein** [comment]
Modify thermal-debug-dump-ubuntu.sh to add -b thermald_2_5_devel. And the output of modified thermal-debug-dump-ubuntu.sh is attached

[28111657.tar.gz](https://github.com/intel/thermal_daemon/files/8997429/28111657.tar.gz)
.

**Comment by Kobatw** [comment]
After re-pull, 2.5.0-pre, can't see the error message.  
ubuntu@ubuntu:~$ sudo systemctl status thermald.service 
● thermald.service - Thermal Daemon Service
     Loaded: loaded (/lib/systemd/system/thermald.service; enabled; vendor preset: enabled)
     Active: active (running) since Thu 2022-07-07 16:00:35 CST; 1min 9s ago
   Main PID: 980 (thermald)
      Tasks: 4 (limit: 18679)
     Memory: 4.4M
        CPU: 18ms
     CGroup: /system.slice/thermald.service
             └─980 //sbin/thermald --systemd --dbus-enable --adaptive

 七  07 16:00:35 ubuntu systemd[1]: Starting Th
[07160225.tar.gz](https://github.com/intel/thermal_daemon/files/9061706/07160225.tar.gz)
ermal Daemon Service...
 七  07 16:00:35 ubuntu systemd[1]: Started Thermal Daemon Service.
 七  07 16:00:35 ubuntu thermald[980]: 32 CPUID levels; family:model:stepping 0x6:b7:0 (6:183:0)
 七  07 16:00:35 ubuntu thermald[980]: Polling mode is enabled: 4
ubuntu@ubuntu:~$ thermald --version
2.5.0-pre
