### ISSUE TITLE
sensor/zone/cooling device types

### ISSUE THREAD

**Issue by dannyp777** [intel/thermal_daemon#454]
Why is it that thermald identifies sensors, zones and cooling-devices by type rather than name or ID? 
If I add 3 different acpitz thermal zones (as per my sysfs) all of the same type they all get rolled into one, and it just picks one of the acpitz sensors at random.  
So to maintain the same thermal zones as in the sysfs I need to create novel, unique zone names for each of the zone types. But then -- why call it a zone type??? 
It's also confusing because each thermal zone has a type in the sysfs, so it is natural to assume that type should be used as the zone type in thermal-conf.xml
Very counter-intuitive.

**Comment by spandruvada** [comment]
You have three acpitz? Is this some server system? Thermald doesn't work on such server systems.

**Comment by spandruvada** [comment]
If you mean identify by thermal_zone_$ID, cooling_device_$ID, then you can't. They are logical number assigned by kernel based on module loading order. They can change as modules loads in parallel. Even for built-in like you see for acpictz, a new built in thermal driver will change ID.
You can use x86_package temp instead of acpictz.

**Comment by spandruvada** [comment]
Question answered.
