### ISSUE TITLE
Thermald is being too conservative on high temperatures

### ISSUE THREAD

**Issue by roobre** [intel/thermal_daemon#49]
Hi,
I'm currently using thermald `1.3` on an HP Laptop with an `Intel(R) Core(TM) i7-3610QM CPU @ 2.30GHz` and Archlinux (`Linux 3.18.2-2-ARCH #1 SMP PREEMPT x86_64 GNU/Linux`) as OS.
Thermald behaves perfectly with normal use, even with high CPU usage, keeping my laptop under 50ºC on most cases and sometimes even under 45ºC, using little fan usage or even shutting it off.

But, when I play games which cause high GPU activity, the temperature goes up to 85ºC with ease, and the fan is still as quiet as when its over 50.

Of course this behavior is not desirable, as the metallic surface of the laptop starts to burn on touch and the electronics start to suffer a bit, and I think Thermald should speed up the fan when temperature goes over a certain thresold, as other cooling methods will obviously not decrease GPU temperature.

[Link to my config file](http://pastebin.com/jKnZDLEp)

Regards, Roberto.

**Comment by XapaJIaMnu** [comment]
I'm having the same issue. Did you manage to solve the problem somehow?

**Comment by roobre** [comment]
Well, I figured out I could create a thermal zone for more than, say, 65ºC, and tell thermald to actively use the fan inside it. Unfortunately, the documentation for `thermal-conf.xml` is pretty limited, so I've not found the way to actually do it.

As a workaround, I turn off thermald before playing games and turn it back on when I finish.

If I finally find out how to tell thermald to actually use the fan I'll post the conf snippet here.

Regards, Roberto.

**Comment by XapaJIaMnu** [comment]
Do you know which of thermald cooling devices is the fan? Could it be the so called "Processor"?

**Comment by roobre** [comment]
Only god (or the sysfs kernel developers) know. On my desktop, for example, I have 2 case fans and the CPU cooler. The output of `cat /sys/class/thermal/cooling_device*/type` is:

    Processor
    Processor
    Processor
    Processor
    Fan
    Fan
    Fan
    Fan
    Fan
    intel_powerclamp

Which actually makes sense, as my mobo has 4 slots for case fans and one for the CPU cooler. I verified his hypothesis by issuing `cat /sys/class/thermal/cooling_device*/cur_state`, which returned:

    0
    0
    0
    0
    0
    0
    1
    1
    1
    -1

(This is two fans and the CPU cooler are active (1), the others are not (0) (because there are no actual fan plugged into that socket).

HOWEVER, and this is where things get weird, on my laptop there are no cooling devices typed as "Fan". Only a lot of "Processor"s:

    Processor
    Processor
    Processor
    Processor
    Processor
    Processor
    Processor
    Processor
    intel_powerclamp
    LCD

and

    0
    0
    0
    0
    0
    0
    0
    0
    -1
    45

So... welp. I'm afraid I'm as clueless as you :\

**Comment by dirtyepic** [comment]
I have the same issue with Dell Latitude laptop that has a i7-4910MQ.  I regularly see temps of 90-95ºC when compiling.  It usually takes about 3 seconds for the fans to start spinning up, and maybe 5-6s for them to hit max, at which point it's too late because either thermald has disabled turbo mode through the pstate controller or the kernel has freaked out and forcibly throttled the cpu.  Now it's cool again so the fans cut out, just in time for the cpu to be unthrottled and jump immediately back up into the 90's.  Repeat, repeat, repeat.

Although there are two fans on this laptop I don't seem to have a way of controlling them (the i8k driver exposes the fan info, but any writes I make to the pwm files are immediately overwritten).

This is typical:
/sys/class/thermal/thermal_zone0    25 (acpitz)
/sys/class/thermal/thermal_zone1    94 (x86_pkg_temp)
/sys/class/hwmon/hwmon0/temp1_input 25 (acpitz)
/sys/class/hwmon/hwmon1/temp1_input 47 (nouveau)
/sys/class/hwmon/hwmon2/temp1_input 95 (coretemp)
/sys/class/hwmon/hwmon2/temp2_input 88 (coretemp)
/sys/class/hwmon/hwmon2/temp3_input 94 (coretemp)
/sys/class/hwmon/hwmon2/temp4_input 95 (coretemp)
/sys/class/hwmon/hwmon2/temp5_input 89 (coretemp)
/sys/class/hwmon/hwmon3/temp1_input 91 (i8k)
/sys/class/hwmon/hwmon3/temp2_input 46 (i8k)
/sys/class/hwmon/hwmon3/temp3_input 58 (i8k)
/sys/class/hwmon/hwmon3/temp4_input 46 (i8k)
/sys/class/hwmon/hwmon3/pwm1 128 (i8k fan)
/sys/class/hwmon/hwmon3/pwm2 128 (i8k fan)
/sys/class/hwmon/hwmon3/fan1_input 2093 (i8k fan)
/sys/class/hwmon/hwmon3/fan2_input 2099 (i8k fan)
/sys/devices/system/cpu/intel_pstate/no_turbo 0
cpu MHz		: 3099.941
cpu MHz		: 3099.941
cpu MHz		: 3099.941
cpu MHz		: 3099.941
cpu MHz		: 3099.941
cpu MHz		: 3099.941
cpu MHz		: 3099.941
cpu MHz		: 3099.941

(my acpi thermal zone seems to be broken - it's always "25".  But I built a new kernel without support for acpitz and it made no difference, so I know that's not the problem)

$ cat /sys/class/thermal/cooling_device*/type
intel_powerclamp
Processor
Processor
Processor
Processor
Processor
Processor
Processor
Processor

I've tried several different config files, different kernel options, etc. etc.  The only thing that has helped was to give Processor priority above intel_pstate in thermal-cpu-cdev-order.  That seems to keep the temps around 80-85 by stepping down the MHz slightly when it gets too hot, and seems to smooth out the fans a bit, but I still get overheating on long compiles.  Or I can disable turbo mode and the temps never go above 75º, but my compiling takes several minutes longer to complete, which I don't really like because I spent extra to upgrade the processor when I got this laptop, so it'd be nice if it worked.

**Comment by spandruvada** [comment]
Closing older issues, reopen if you need to.
