### ISSUE TITLE
QUESTION: Kernel Has Thermal Support So Why thermal_daemon?

### ISSUE THREAD

**Issue by ghost** [intel/thermal_daemon#52]
Hi,

I ran into this project recently, but I really don't understand the need for this, since the kernel supplies thermal support?

What is the benefits, reason for the thermal_daemon over what the kernel supports?

thanks

**Comment by meuwe** [comment]
Hi,

Has anyone had a chance to see this? I'm still trying to understand the need for this, when the kernel already has the support?

thank you

**Comment by daringer** [comment]
I think it's pretty obvious: the classic separation between userland and kernelland. Whilst a kernel module should primarily provide an interface (for some hardware), the userland applications may (ab)use this interface to control this particular piece of hardware. I know,  more an "we-do-it-like-this-because-we-have-always-done-it-like-that" argument .... Nevertheless the're others: Security is obvious I guess: accessing kernel-space could leave doors open or similar. multiple users could need access, even at the same time, mutexing?locking? inside the kernel, dependent on user-interaction, please no ;) further I wouldn't like my kernel to lose responsiveness because of some (cpu-)expensive software fighting for the same (priviledged) resources. The kernel is in fact often described as the inferface between hardware and the user. Finally, bigger infrastructure setups force the userland-applications to interact through varying mediums --- not being the classic kernel task I guess ;)

**Comment by RJVB** [comment]
I think the question was: why use an external thermald if the kernel apparently already has temperature control?
The kernel sits closer to the hardware, has the appropriate drivers AND might have knowledge not available to userland applications which could help in temperature control.

You could (almost) take the question 1 step further: why bother with software-based temperature control if the firmware (BIOS/[U]EFI/...) already handles it?
