### ISSUE TITLE
thermald fails on ASUS M5A78L-M LX with AMD FX-6100

### ISSUE THREAD

**Issue by ksarkies** [intel/thermal_daemon#84]
I'm finding problems with thermald on this particular machine, which experiences heat related crashes. The debug mode shows that it is complaining about unsupported CPU, but when the --ignore-cpuid-check is used, it drops out without setting any zones etc.

It actually worked with the stock Ubuntu version just before the new year, but stopped working no doubt due to an upgrade of thermald to 1.4.3.

I've worked back painfully through the commits on GitHub and discovered that thermald stops working with the commit 92172961576a1c29fd5af68469959dd0fda01353 on Sep 9, 2014. The commit before that runs apparently OK.

The first output is without the cpuid check, the second with it. thermald-conf.xml doesn't seem to affect its ability to run.

[thermald-1.txt](https://github.com/01org/thermal_daemon/files/160291/thermald-1.txt)
[thermald-2.txt](https://github.com/01org/thermal_daemon/files/160292/thermald-2.txt)
[thermal-conf.txt](https://github.com/01org/thermal_daemon/files/160294/thermal-conf.txt)

Please let me know if there is any other info that is of use.

cheers, Ken
ps thanks for the work you are doing on this. Without it my desktop is all but useless.

**Comment by spandruvada** [comment]
Since I can't test on AMD platforms, unless someone sends a change I can't add to whitelist.
Meanwhile it can be used with --ignore-cpuid-check option.

**Comment by cooper151288** [comment]
Hi, I have it working on an FX 8350, using k10temp as the thermal sensor and PID (I'll suggest a better algorithm when i get a bit better with the code for it, my math is sound) on the "powersave bias" param of the ondemand governor . I have to set the ignore cpuid check. I set the thermal zone type, the thermal sensor sensor type and the trip point sensor type all to "cpu" (lowercase" as it creates that zone automatically. Try this and see if it works for you. The powersave bias settings allow a much finer granularity of cpufreq control. Test that with TurionPowerControl with the "tpc -CM" command. That will report the time that the cpu spends in each P-state The main problem I have with my fam15h processor is that since there are k10temp and fam15h_power loaded from this firmware, it cannot be guaranteed which way round they will load, but using the bus address (read the BKDG), it will remain invariant.

**Comment by spandruvada** [comment]
Hi,

When you make it work and some config file, I can add to man page for
example configurations.

Thanks,
Srinivas

**Comment by cooper151288** [comment]
[thermal-conf.txt](https://github.com/intel/thermal_daemon/files/1182687/thermal-conf.txt)
I have been using this so far, still need to test changing over to using /sys/devices/pci...../18.3. Im not sure if wildcarding after the hwmon directory is a great idea, hence me using /sys/class/hwmon. I find the powersave bias a far better cooling device than the cpufreq on my AMD system, as it allows a mix of P-states across the CPU, and lowers the P-state residency timesas the system gets to the temperature. I've also hard-set the max, passive and setpoint (in the /var/run files) to Tctl=65. and the processor rarely reaches Tctl=70 (the recommended maximum, hard throttling occcurs at Tctl=90). The PID control must be tuned for each system first though. What works on my system (stock cooler, raised turbo P-state frequency (pb0=4500 from 4200, pb1=4300 from 4100), stock normal frequency, stock voltage) will likely NOT work on another system. A way of setting this up while the program is live would be brilliant but I've tried doing something similar myself and it's really hard. Note that this config will NOT work unless you are on the "ondemand" governor.

**Comment by cooper151288** [comment]
It looks like the intel P-state driver has a tunable max target frequency like ondemand. If its anything like the ondemand system, you might like the result. Please test this on an intel system, as I am getting both better performance and tighter thermal regulation.
